settings:
  remove_quotes_in_frontmatter:
   - "false"
pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "permalink"
    - "override"
    - "codelabs"
    - "tags"
    - "authors"
    - "translated"
segments:
  ignore_frontmatter_keys:
    - "authors"
    - "translated"
    
    ignore_patterns:
     - !ruby/regexp /{%\s?([a-zA-Z0-9\.\-\?\'\"\,\!\s\/]*)\s?%}/
     - !ruby/regexp /{%\s?end([a-zA-Z0-9\.\-\?\'\"\,\!\s]*)\s?%}/
     - !ruby/regexp /{%\s?AssessmentCallout([a-zA-Z0-9\.\-\?\'\"\,\!\s]*)\s?%}/

  paths:
  - source: "src/site/content/en"
    include:
    - "lighthouse-performance/**/*.md"
