settings:
  remove_quotes_in_frontmatter:
   - "false"
segments:
  ignore_frontmatter_keys:
  - "authors"
  - "translated"
  - "tags"

  paths:
  - source: "src/site/content/en"
    include:
    - "lighthouse-performance/**/*.md"
